version: 2
updates:
- directory: "/"
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: weekly
  allow:
    - dependency-type: "production"
  ignore:
    - dependency-name: '*'
      update-types: ['version-update:semver-patch']
